name: Playwright Cucumber Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ui-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run UI tests
        run: npx cucumber-js tests/features/ui/*.feature
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ui-test-report
          path: playwright-report/
          retention-days: 30

  api-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run API tests
        run: npx cucumber-js tests/features/api/*.feature
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api-test-report
          path: playwright-report/
          retention-days: 30
